/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
import java.util.ArrayList;
public class EvenFibonacciNumbers {
    public static void main(String[] args){
        //generate list of fibonacci numbers less than 4 million
        //iterate through list and find even numbered ones
        ArrayList<Integer> fib = new ArrayList<>();
        fib.add(1);
        fib.add(2);
        int term=0;
        while(term < 4000000){
            term = fib.get(fib.size()-1)+fib.get(fib.size()-2);
            fib.add(term);
        }
        int sum = 0;
        for(int i=0;i<fib.size();i++){
            if(fib.get(i)%2==0) sum += fib.get(i);
        }
        System.out.println(sum);
    }
}
