#Names: Vivian and Karthik
# 8/28/2019

from pyKarel import *

wld = World("school")
lisa = Robot(wld)
pete = Robot(wld, 4, 5, south, 0)
lisa.move()
lisa.move()
lisa.turnLeft()
lisa.move()
lisa.turnLeft()
lisa.move()
lisa.pickBeeper()
lisa.turnLeft()
lisa.turnLeft()
lisa.move()
lisa.turnLeft()
lisa.turnLeft()
lisa.turnLeft()
lisa.move()
lisa.turnLeft()
lisa.move()
lisa.move()
lisa.move()
lisa.turnLeft()
lisa.move()
lisa.move()
lisa.move()
lisa.turnLeft()
lisa.move()
lisa.move()
lisa.turnLeft()
lisa.turnLeft()
lisa.turnLeft()
lisa.move()
lisa.putBeeper()
pete.pickBeeper()
pete.move()
pete.turnLeft()
pete.move()
pete.move()
pete.turnLeft()
pete.move()
pete.move()
pete.turnLeft()
pete.turnLeft()
pete.turnLeft()
pete.move()
pete.move()
pete.turnLeft()
pete.move()
pete.turnLeft()
pete.move()
pete.move()
pete.turnLeft()
pete.turnLeft()
pete.turnLeft()
pete.move()
pete.move()
pete.turnLeft()
pete.move()
pete.move()
pete.putBeeper()
pete.turnLeft()
pete.turnLeft()
pete.move()

wld.mainloop()